# ========================
# SERVER
# ========================
server.port=${PORT:10000}

# ========================
# DATABASE - PostgreSQL (Neon)
# ========================
# Just put your Neon URL directly here for testing
spring.datasource.url=jdbc:postgresql://ep-dry-credit-aj77ca8h-pooler.c-3.us-east-2.aws.neon.tech/freelance-marketplace-db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_O43PKHzRSbJT
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================
# SECURITY / JWT
# ========================
app.jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
app.jwt.expiration-ms=86400000

# ========================
# CORS
# ========================
app.cors.allowed-origins=https://freelancer-frontend-hdt5efzut-shubhamp2611s-projects.vercel.app
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
app.cors.allow-credentials=true